version: '3'

services:
    controller:
        container_name: "edget-controller"
        restart: "always"
        image: "edgegallery/edget-be:latest"
        ports:
            - "8080:8080"
        environment:
            OCOMP_IP: testcase-feature1
            OCOMP_PORT: 50051
        links:
            - testcase-feature1

    testcase-feature1:
        container_name: "testcase-feature1"
        restart: "always"
        image: "edgegallery/edget-feature1-testcase:latest"
        ports:
            - "50051:50051"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
